create database grocery_store_management;
use grocery_store_management;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
 
-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
select * from supplier;
select * from categories;
select * from employees;
select * from customers;
select * from products;
select * from orders;
select * from order_details;
-- Analysis Questions

-- 1️. Customer Insights

-- Gain an understanding of customer engagement and purchasing behavior.

-- 1)How many unique customers have placed orders?
select distinct(cust_name)
from customers 
inner join orders on customers.cust_id = orders.cust_id;

-- 2)Which customers have placed the highest number of orders?
select cust_name,count(*)
from customers 
inner join orders on customers.cust_id = orders.cust_id 
group by cust_name order by count(*) desc limit 1;

-- 3)What is the total and average purchase value per customer?
select cust_name,sum(total_price),avg(total_price) from customers inner join 
orders on customers.cust_id = orders.cust_id 
inner join order_details on orders.ord_id = order_details.ord_id
group by cust_name;

-- 4)Who are the top 5 customers by total purchase amount?
select cust_name,sum(total_price) from customers inner join 
orders on customers.cust_id = orders.cust_id inner join
order_details on orders.ord_id = order_details.ord_id
group by cust_name 
order by sum(total_price) 
desc limit 5;

-- 2. Product Performance

-- Evaluate how well products are performing in terms of sales and revenue.

-- 5)How many products exist in each category?
select cat_name,count(prod_name) from categories inner join 
products on categories.cat_id = products.cat_id
group by cat_name;

-- 6)What is the average price of products by category?
select cat_name,avg(price) from categories inner join 
products on categories.cat_id = products.cat_id
group by cat_name;

-- 7)Which products have the highest total sales volume (by quantity)?
select prod_name,sum(quantity) from categories inner join
products on categories.cat_id = products.cat_id inner join
order_details on products.prod_id = order_details.prod_id
group by prod_name order by sum(quantity) desc;

-- 8)What is the total revenue generated by each product?
select prod_name,sum(total_price) from products inner join 
order_details on products.prod_id = order_details.prod_id
group by prod_name;

-- 9)How do product sales vary by category and supplier?
select sup_name,cat_name,sum(total_price) from supplier inner join
products on supplier.sup_id = products.sup_id inner join 
order_details on products.prod_id = order_details.prod_id
inner join categories on products.cat_id=categories.cat_id
group by sup_name,cat_name
order by sum(total_price) desc;

-- 3. Sales and Order Trends

-- Analyze business performance through orders and revenue over time.

-- 10)How many orders have been placed in total?
select count(*) from orders;

-- 11)What is the average value per order?
with iykyk as (select ord_id,sum(total_price) as total_sales from order_details
group by ord_id) 
select avg(total_sales) from iykyk;

-- 12)On which dates were the most orders placed?
select order_date,count(*) from orders
group by order_date 
order by count(*) 
desc limit 1;

-- 13)What are the monthly trends in order volume and revenue?
select * from orders;
select * from order_details;
SELECT month(DATE_FORMAT(
         STR_TO_DATE(order_date, '%m/%d/%Y'),
         '%Y-%m-%d'
       )) as month, count(*) as No_of_orders,sum(total_price)
FROM orders inner join order_details on orders.ord_id=order_details.ord_id
 group by month order by month;

-- 14)How do order patterns vary across weekdays and weekends?
SELECT dayname(DATE_FORMAT(
         STR_TO_DATE(order_date, '%m/%d/%Y'),
         '%Y-%m-%d'
       )) as day_name,count(*)
FROM orders group by day_name;

-- 4️. Supplier Contribution

-- Identify the most active and profitable suppliers.

-- 15)How many suppliers are there in the database?
select count(sup_name) from supplier;

-- 16)Which supplier provides the most products?
select sup_name,count(*) from supplier inner join
products on supplier.sup_id = products.sup_id
group by sup_name
order by count(*) desc;

-- 17)What is the average price of products from each supplier?
select sup_name,avg(price) from supplier inner join
products on supplier.sup_id = products.sup_id
group by sup_name;

-- 18)Which suppliers contribute the most to total product sales (by revenue)?
select sup_name,sum(price) from supplier inner join
products on supplier.sup_id = products.sup_id
group by sup_name
order by sum(price) desc;

-- 5️. Employee Performance

-- Assess how employees are handling and influencing sales.

-- 19)How many employees have processed orders?
select emp_name,count(*) from employees inner join
orders on employees.emp_id = orders.emp_id
group by emp_name;

-- 20)Which employees have handled the most orders?
select emp_name,count(*) from employees inner join
orders on employees.emp_id = orders.emp_id
group by emp_name
order by count(*) desc
limit 1;

-- 21)What is the total sales value processed by each employee?
select emp_name,sum(total_price) from employees inner join
orders on employees.emp_id = orders.emp_id inner join 
order_details on orders.ord_id = order_details.ord_id
group by emp_name;

-- 22)What is the average order value handled per employee?
select emp_name,avg(total_price) from employees inner join
orders on employees.emp_id = orders.emp_id inner join 
order_details on orders.ord_id = order_details.ord_id
group by emp_name;

-- 6️. Order Details Deep Dive

-- Explore item-level sales patterns and pricing behavior.

-- 23)What is the relationship between quantity ordered and total price?
select quantity,total_price from order_details
group by quantity,total_price
order by quantity desc;

-- 24)What is the average quantity ordered per product?
select prod_name,avg(quantity) from products inner join
order_details on products.prod_id = order_details.prod_id
group by prod_name;

-- 25)How does the unit price vary across products and orders?
select products.prod_id,price,each_price from products inner join
order_details on products.prod_id = order_details.prod_id;